DROP DATABASE IF EXISTS `z11_elearning`;
CREATE DATABASE `z11_elearning` CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `z11_elearning`;

-- table
DROP TABLE IF EXISTS `PERMISSION`;
CREATE TABLE IF NOT EXISTS `PERMISSION`(
    `PMSCODE` VARCHAR(50) NOT NULL,
    `PMSDESC` VARCHAR(254),
    PRIMARY KEY(`PMSCODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- table
DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE IF NOT EXISTS `ROLE`(
    `ROLECODE` VARCHAR(50) NOT NULL,
    `ROLEDESC` VARCHAR(254),
    PRIMARY KEY(`ROLECODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- table
DROP TABLE IF EXISTS `ROLEPERMISSION`;
CREATE TABLE IF NOT EXISTS `ROLEPERMISSION`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `ROLECODE` VARCHAR(50) NOT NULL,
    `PMSCODE` VARCHAR(254) NOT NULL,
    `CREATEDTIME` DATETIME,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE ROLEPERMISSION ADD CONSTRAINT ROLEPERMISSION_ROLE
FOREIGN KEY (`ROLECODE`)
REFERENCES ROLE(`ROLECODE`)
  ON DELETE CASCADE;

ALTER TABLE ROLEPERMISSION ADD CONSTRAINT ROLEPERMISSION_PERMISSION
FOREIGN KEY (`PMSCODE`)
REFERENCES PERMISSION(`PMSCODE`)
  ON DELETE CASCADE;



-- table
DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USERID` VARCHAR(254) NOT NULL,
    `EMAIL` VARCHAR(254) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(254) NOT NULL,
    `BALANCE` INT(11) NOT NULL DEFAULT 0,
    `ROLECODE` VARCHAR(50),
    `CREATEDTIME` DATETIME,
    PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE USER ADD CONSTRAINT USER_ROLE
FOREIGN KEY (`ROLECODE`)
REFERENCES ROLE(`ROLECODE`)
  ON DELETE SET NULL;

ALTER TABLE USER ADD INDEX `EMAIL`(`EMAIL`);
ALTER IGNORE TABLE USER ADD UNIQUE (`EMAIL`);
ALTER IGNORE TABLE USER ADD UNIQUE (`USERID`);
